### ISSUE TITLE
npm run bundle error

### ISSUE THREAD

**Issue by imsheng** [casesandberg/react-color#549]
```
$ npm run bundle

> react-color@3.0.0-beta.3 bundle C:\Users\sheng\Desktop\react-color
> rollup -c scripts/rollup.config.js


src/index.js → dist/react-color.min.js...
[!] (commonjs plugin) SyntaxError: Unexpected token (4:14) in C:\Users\sheng\Desktop\react-color\src\index.js
src\index.js (4:14)
SyntaxError: Unexpected token (4:14) in C:\Users\sheng\Desktop\react-color\src\index.js
    at error (C:\Users\sheng\Desktop\react-color\node_modules\rollup\dist\rollup.js:185:14)
    at Promise.resolve.then.catch.err (C:\Users\sheng\Desktop\react-color\node_modules\rollup\dist\rollup.js:9510:6)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-color@3.0.0-beta.3 bundle: `rollup -c scripts/rollup.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-color@3.0.0-beta.3 bundle script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\sheng\AppData\Roaming\npm-cache\_logs\2018-10-06T05_46_56_975Z-debug.log

```

**Comment by shio-yaamaa** [comment]
Changing line 4 in `src/index.js` from

```javascript
export default, { default as ChromePicker } from './components/chrome/Chrome'
```

to

```javascript
export { default, default as ChromePicker } from './components/chrome/Chrome'
```

worked for me but I’m not sure if it’s a valid syntax.
