### ISSUE TITLE
dependency (?) error (lodash/lang/isString)

### ISSUE THREAD

**Issue by Sajam** [casesandberg/react-color#79]
I've done `npm install react-color --save` - it saved `react-color` version `^1.3.4` (based on `package.json`). Then, when I try to build my app with `browserify` (via `gulp`) it fails with following error message:

> events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Cannot find module 'lodash/lang/isString' from '/home/[...]/node_modules/react-color/modules/react-material-design/lib/components'
    at /home/[...]/node_modules/browserify/node_modules/resolve/lib/async.js:46:17
    at process (/home/[...]/node_modules/browserify/node_modules/resolve/lib/async.js:173:43)
    at ondir (/home/[...]/node_modules/browserify/node_modules/resolve/lib/async.js:188:17)
    at load (/home/[...]/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/[...]/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
    at /home/[...]/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
    at Object.oncomplete (fs.js:107:15)

Software versions:
* browserify - 11.0.1
* gulp - 3.9.0
* npm - 2.14.12
* node - 0.10.25

**Comment by casesandberg** [comment]
This error is because I am using the lodash babel plugin. I am in the process of reverting it.

**Comment by casesandberg** [comment]
This has been fixed in `react-color@1.3.5`
