### ISSUE TITLE
Color-Picker Eyedropper is not working for Windows OS Chrome

### ISSUE THREAD

**Issue by rishonide-swivel** [casesandberg/react-color#879]
Got this error when extracting color from eye-dropper
`index.js:2178 TypeError: Cannot read properties of undefined (reading 'trim')
    at convertRgbToHex (convertRgbToHex.ts:4:1)
    at ViviTemplateVariationViewer.<anonymous> (index.tsx:954:1)
    at step (style.scss?2d85:26:1)
    at Object.next (style.scss?2d85:26:1)
    at fulfilled (style.scss?2d85:26:1)`

This works fine in ubuntu

**Comment by rishonide-swivel** [comment]
> Got this error when extracting color from eye-dropper `index.js:2178 TypeError: Cannot read properties of undefined (reading 'trim') at convertRgbToHex (convertRgbToHex.ts:4:1) at ViviTemplateVariationViewer.<anonymous> (index.tsx:954:1) at step (style.scss?2d85:26:1) at Object.next (style.scss?2d85:26:1) at fulfilled (style.scss?2d85:26:1)`
> 
> This works fine in ubuntu
